version: "3"

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd /;uvicorn src.main:api --host 0.0.0.0 --port=80'
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    
    ports:
      - "5005:80"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=insurance
      - POSTGRES_PASSWORD=abc123
    expose:
      - "5432"
